  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module monster_hunter::monster_hunter_monster_type {

  use sui::bcs::{BCS, to_bytes, peel_enum_tag};

  public enum MonsterType has copy, drop, store {
        Caterpillar,Eagle,Rat
    }

  public fun new_caterpillar(): MonsterType {
    MonsterType::Caterpillar
  }

  public fun new_eagle(): MonsterType {
    MonsterType::Eagle
  }

  public fun new_rat(): MonsterType {
    MonsterType::Rat
  }

  public fun encode(self: MonsterType): vector<u8> {
    to_bytes(&self)
  }

  public fun decode(bytes: &mut BCS): MonsterType {
    match(peel_enum_tag(bytes)) {
            0 => MonsterType::Caterpillar,
            1 => MonsterType::Eagle,
            2 => MonsterType::Rat,
            _ => abort,
        }
  }
}
