  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module monster_hunter::monster_hunter_terrain_type {

  use sui::bcs::{BCS, to_bytes, peel_enum_tag};

  public enum TerrainType has copy, drop, store {
        Boulder,None,TallGrass
    }

  public fun new_boulder(): TerrainType {
    TerrainType::Boulder
  }

  public fun new_none(): TerrainType {
    TerrainType::None
  }

  public fun new_tallgrass(): TerrainType {
    TerrainType::TallGrass
  }

  public fun encode(self: TerrainType): vector<u8> {
    to_bytes(&self)
  }

  public fun decode(bytes: &mut BCS): TerrainType {
    match(peel_enum_tag(bytes)) {
            0 => TerrainType::Boulder,
            1 => TerrainType::None,
            2 => TerrainType::TallGrass,
            _ => abort,
        }
  }
}
